name: Node.js App

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t wasiabdullah111/node-app .

      - name: Push Docker image
        run: docker push wasiabdullah111/node-app

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.EC2_SSH_KEY_BASE64 }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            docker pull wasiabdullah111/node-app
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 3000:3000 --name node-app wasiabdullah111/node-app
          EOF
